version: '3.1'
services:
    php:
        build: docker/php
        working_dir: /application
        volumes:
            - './php-project:/application'

    node:
        build: docker/node
        working_dir: /application
        tty: true
        volumes:
            - './vue-project:/application'
        ports:
            - '5173:5173'